apiVersion: v1
kind: Service
metadata:
  name: flask-nginx-service
spec:
  type: NodePort
  selector:
    app: flask-nginx
  ports:
    - protocol: TCP
      port: 80           # The service listens on port 80
      targetPort: 5000   # Your Flask app runs on port 5000
      nodePort: 31189    # External access via Minikube
